### ISSUE TITLE
Out the box it does not work.

### ISSUE THREAD

**Issue by jarrettj** [pmuens/serverless-crud#4]
sls install --url https://github.com/pmuens/serverless-crud
sls deploy

curl https://7u10uza9kb.execute-api.us-east-1.amazonaws.com/dev/todos 
Output:
{"message": "Internal server error"}

CloudWatch logs:

```
Unable to import module 'handler': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/handler.js:3:16)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
```

**Comment by jarrettj** [comment]
Got it to work eventually. I changed my region to eu-west, but forgot to update the DynamoDB table region as well.
